spring:
  application:
    name: eurekaserver

server:
  port: 8761

eureka:
  client:
    register-wiht-eureka: false
    fetch-registry: false
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF

